[package]
name = "c_implifier"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ! DEPRECATED
#bevy = "0.17.2"
colored = "3.0.0"
terminal_size = "0.4.3"

